on:
  release:
    types:
    - published

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: release
      uses: ecrousseau/go-release@v0.0.8
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
      